service: max-kinesis-consumers

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - kinesis:PutRecord
      Resource:
        Fn::GetAtt:
          - Stream
          - Arn
  
functions:
  producer:
    handler: handler.producer
    memorySize: 128
    environment:
      STREAM_NAME:
        Ref: Stream
  consumer1:
    handler: handler.consumer1
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - Stream
              - Arn
          batchSize: 100
          startingPosition: TRIM_HORIZON
    memorySize: 128
    environment:
      STREAM_NAME:
        Ref: Stream
  consumer2:
    handler: handler.consumer2
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - Stream
              - Arn
          batchSize: 100
          startingPosition: TRIM_HORIZON
    memorySize: 128
    environment:
      STREAM_NAME:
        Ref: Stream
  consumer3:
    handler: handler.consumer3
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - Stream
              - Arn
          batchSize: 100
          startingPosition: TRIM_HORIZON
    memorySize: 128
    environment:
      STREAM_NAME:
        Ref: Stream
  consumer4:
    handler: handler.consumer4
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - Stream
              - Arn
          batchSize: 100
          startingPosition: TRIM_HORIZON
    memorySize: 128
    environment:
      STREAM_NAME:
        Ref: Stream
  consumer5:
    handler: handler.consumer5
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - Stream
              - Arn
          batchSize: 100
          startingPosition: TRIM_HORIZON
    memorySize: 128
    environment:
      STREAM_NAME:
        Ref: Stream
  consumer6:
    handler: handler.consumer6
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - Stream
              - Arn
          batchSize: 100
          startingPosition: TRIM_HORIZON
    memorySize: 128
    environment:
      STREAM_NAME:
        Ref: Stream

package:
  exclude:
    - node_modules/**
    - '!node_modules/highland/**'
    - '!node_modules/util-deprecate/**'
    - '!node_modules/uuid/**'

resources:
  Resources:
    Stream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${self:provider.stage}-${self:service}-stream
        RetentionPeriodHours: 24
        ShardCount: 1
  Outputs:
    streamName:
      Value: 
        Ref: Stream
    streamArn:
      Value: 
        Fn::GetAtt:
          - Stream
          - Arn